"""create user table

Revision ID: 0e77998eeb82
Revises: 
Create Date: 2026-03-25 20:52:36.334282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e77998eeb82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Medi_History')
    op.drop_table('Appointment')
    op.drop_table('Prescription')
    op.drop_table('Room')
    op.drop_table('Patient')
    op.drop_table('Prescription_Item')
    op.drop_table('Medicine')
    op.drop_table('Available_Slots')
    op.drop_table('TimeSlot')
    op.drop_table('Doctor')
    op.alter_column('User', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'profile_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'is_active',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.create_unique_constraint(None, 'User', ['Email'])
    op.drop_table_comment(
        'User',
        existing_comment='All user of the clinic management system',
        schema=None
    )
    op.drop_column('User', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'User',
        'All user of the clinic management system',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'is_active',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'profile_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('Doctor',
    sa.Column('doctor_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('professional_bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('years_of_experience', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['User.user_id'], name='Doctor_doctor_id_fkey'),
    sa.PrimaryKeyConstraint('doctor_id', name='Doctor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('TimeSlot',
    sa.Column('slot_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('day_of_weak', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('slot_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('slot_id', name='TimeSlot_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Available_Slots',
    sa.Column('as_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('slot_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['Doctor.doctor_id'], name='Available_Slots_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['Room.room_id'], name='Available_Slots_room_id_fkey'),
    sa.ForeignKeyConstraint(['slot_id'], ['TimeSlot.slot_id'], name='Available_Slots_slot_id_fkey'),
    sa.PrimaryKeyConstraint('as_id', name='Available_Slots_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Medicine',
    sa.Column('medicine_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('medicine_id', name='Medicine_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Prescription_Item',
    sa.Column('item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['Medicine.medicine_id'], name='Prescription_Item_medicine_id_fkey'),
    sa.ForeignKeyConstraint(['prescription_id'], ['Prescription.prescription_id'], name='Prescription_Item_prescription_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', name='Prescription_Item_pkey')
    )
    op.create_table('Patient',
    sa.Column('patient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('patient_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['User.user_id'], name='Patient_patient_id_fkey'),
    sa.PrimaryKeyConstraint('patient_id', name='Patient_pkey'),
    sa.UniqueConstraint('patient_number', name='Patient_patient_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Room',
    sa.Column('room_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('room_num', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('room_id', name='Room_pkey'),
    sa.UniqueConstraint('room_num', name='Room_room_num_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Prescription',
    sa.Column('prescription_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('appointment _id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_draft', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment _id'], ['Appointment.appointment_id'], name='Prescription_appointment _id_fkey'),
    sa.ForeignKeyConstraint(['doctor_id'], ['Doctor.doctor_id'], name='Prescription_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.patient_id'], name='Prescription_patient_id_fkey'),
    sa.PrimaryKeyConstraint('prescription_id', name='Prescription_pkey')
    )
    op.create_table('Appointment',
    sa.Column('appointment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('as_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_draft', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['as_id'], ['Available_Slots.as_id'], name='Appointment_as_id_fkey'),
    sa.ForeignKeyConstraint(['doctor_id'], ['Doctor.doctor_id'], name='Appointment_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.patient_id'], name='Appointment_patient_id_fkey'),
    sa.PrimaryKeyConstraint('appointment_id', name='Appointment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Medi_History',
    sa.Column('patient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('diagnosis notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('health status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['Appointment.appointment_id'], name='Medi_History_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.patient_id'], name='Medi_History_patient_id_fkey'),
    sa.PrimaryKeyConstraint('patient_id', 'appointment_id', name='Medi_History_pkey')
    )
    # ### end Alembic commands ###
