"""update medical history and user model

Revision ID: 6ecbb44759e2
Revises: 97bdc8b54bf6
Create Date: 2026-10-05 23:21:12.804415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecbb44759e2'
down_revision: Union[str, None] = '97bdc8b54bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AvailableSlots', 'expected_appointments',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('MedicalHistory', sa.Column('history_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'MedicalHistory', ['appointment_id'])
    op.add_column('User', sa.Column('user_type', sa.String(), nullable=False))
    op.add_column('User', sa.Column('is_guest', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('guest_expires_at', sa.Date(), nullable=True))
    op.drop_column('User', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'guest_expires_at')
    op.drop_column('User', 'is_guest')
    op.drop_column('User', 'user_type')
    op.drop_constraint(None, 'MedicalHistory', type_='unique')
    op.drop_column('MedicalHistory', 'history_id')
    op.alter_column('AvailableSlots', 'expected_appointments',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
