"""remove room table add room_no to timeslot

##

Revision ID: 97bdc8b54bf6
Revises: 926a300d3228
Create Date: 2026-04-10 12:30:03.307819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97bdc8b54bf6'
down_revision: Union[str, None] = '926a300d3228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Appointment', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Appointment', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Appointment', 'as_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Appointment', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Appointment', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('AvailableSlots', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('Doctor', 'professional_bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('Doctor', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Doctor', 'years_of_experience',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('MedicalHistory', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('MedicalHistory', 'diagnosis_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('MedicalHistory', 'health_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('MedicalHistory', 'attachment_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Medicine', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Medicine', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Medicine', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('Medicine', 'quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Medicine', 'is_active',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('Prescription', sa.Column('appointment_id', sa.UUID(), nullable=False))
    op.alter_column('Prescription', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Prescription', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Prescription', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Prescription', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('Prescription_appointment _id_fkey', 'Prescription', type_='foreignkey')
    op.create_foreign_key(None, 'Prescription', 'Appointment', ['appointment_id'], ['appointment_id'])
    op.drop_column('Prescription', 'is_draft')
    op.drop_column('Prescription', 'appointment _id')
    op.alter_column('PrescriptionItem', 'medicine_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('PrescriptionItem', 'prescription_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('PrescriptionItem', 'dosage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('PrescriptionItem', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('PrescriptionItem', 'duration',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('PrescriptionItem', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('TimeSlot', 'room_no',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('TimeSlot', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('User', 'is_active',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('User', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_table_comment(
        'User',
        existing_comment='All user of the clinic management system',
        schema=None
    )
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'User',
        'All user of the clinic management system',
        existing_comment=None,
        schema=None
    )
    op.alter_column('User', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('User', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('TimeSlot', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('TimeSlot', 'room_no',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('PrescriptionItem', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('PrescriptionItem', 'duration',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PrescriptionItem', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PrescriptionItem', 'dosage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PrescriptionItem', 'prescription_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('PrescriptionItem', 'medicine_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.add_column('Prescription', sa.Column('appointment _id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    op.add_column('Prescription', sa.Column('is_draft', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Prescription', type_='foreignkey')
    op.create_foreign_key('Prescription_appointment _id_fkey', 'Prescription', 'Appointment', ['appointment _id'], ['appointment_id'])
    op.alter_column('Prescription', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Prescription', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Prescription', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Prescription', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('Prescription', 'appointment_id')
    op.alter_column('Medicine', 'is_active',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Medicine', 'quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Medicine', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('Medicine', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Medicine', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('MedicalHistory', 'attachment_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('MedicalHistory', 'health_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('MedicalHistory', 'diagnosis_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('MedicalHistory', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Doctor', 'years_of_experience',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Doctor', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Doctor', 'professional_bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('AvailableSlots', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('Appointment', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Appointment', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Appointment', 'as_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Appointment', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('Appointment', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
